### ISSUE TITLE
Question: MIM version

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#99] opened 2020-10-01 12:44 UTC
In TRUD, there are two versions of NHS111 package, which version to be used as reference

**Comment by michael-kainos** [comment] 2020-10-08 11:14
Not sure what is meant by NHS111 package. Will keep this open. Status is NEEDS MORE INFORMATION

**Comment by Kusnaditjung** [comment] 2020-10-08 12:39
actually, there are three NHS 111 DMS in TRUD... 
* NHS 111 Domain Message Specification
* NHS 111 Domain Message Specification (plus CAD to CAD) .. 19 July 2019
* NHS 111 Domain Message Specification Version 2.0 Status RC1 4 December 2015 
(which of this I can use as a reference for the adapter project?

**Comment by michael-kainos** [comment] 2020-10-09 08:55
@Kusnaditjung please use "NHS111DMS-Version2-0-RC1" also, i think we can close this as a duplicate of https://github.com/nhsconnect/integration-adaptor-111/issues/101

**Closed** 2020-10-14 09:19 UTC
